Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: zabbix-
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Zabbix是一款开源的企业级监控解决方案，用于监控多种IT基础设施组件，包括网络设备、服务器、虚拟机和云服务。其主要功能涵盖性能监控、资源使用情况监控以及故障检测和通知。
    Image: 'resources/icons/zabbix.jpg'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: zabbix
    Description: zabbix
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: centos_7_9_x64_20G_alibase_20240403.vhd
    SystemDiskSize: 20
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
        #!/bin/bash
        sudo yum -y update
        sudo yum -y install yum-utils
        sudo mkdir -p /etc/docker
        sudo tee /etc/docker/daemon.json <<-'EOF'
        {
          "registry-mirrors": [
              "https://0vmzj3q6.mirror.aliyuncs.com",
              "https://docker.m.daocloud.io",
              "https://mirror.baidubce.com",
              "https://dockerproxy.com",
              "https://mirror.iscas.ac.cn",
              "https://huecker.io",
              "https://dockerhub.timeweb.cloud",
              "https://noohub.ru",
              "https://vlgh0kqj.mirror.aliyuncs.com"
          ]
        }
        EOF
        sudo systemctl daemon-reload

        yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum makecache fast
        yum install -y git docker-ce jq
        systemctl enable docker
        systemctl start docker

        REPO_URL="https://github.com/aliyun-computenest/quickstart-zabbix"
        CLONE_DIR="/root/quickstart-zabbix"
        git clone "$REPO_URL" "$CLONE_DIR"
        ARGUS_VERSION=3.5.7 /bin/bash -c "$(curl -sS https://cms-agent-ap-southeast-1.oss-ap-southeast-1-internal.aliyuncs.com/Argus/agent_install_ecs-1.7.sh)" >> /root/install_cms_agent.log 2>&1
        cat > /etc/systemd/system/zabbix.service <<EOF
        [Unit]
        Description=Zabbix Service
        Requires=docker.service
        After=docker.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        WorkingDirectory=/root
        ExecStart=/usr/bin/docker compose -f /root/quickstart-zabbix/docker_compose/docker-compose_v3_centos_mysql_latest.yaml up -d
        ExecStop=/usr/bin/docker compose down
        TimeoutStartSec=0

        [Install]
        WantedBy=multi-user.target
        EOF

        systemctl enable zabbix.service
        systemctl start zabbix.service
        systemctl status zabbix.service